#!/usr/bin/env perl
use strict;
use warnings;

require '../static/common.pl';
our $br;

allowed_methods(["GET"]);
print_headers({
    "Content-Type" => "text/html"
});

my $txt = @{spawn_read("date '+%Y-%m-%d %H:%M:%S'")}[1];
printl( e("p", text($txt)) );
