#!/usr/bin/env perl
use strict;
use warnings;

require '../static/rpw_import.pl';
our $br;

allowed_methods(["GET"]);
print_headers({
    "Content-Type" => "text/html"
});

my $txt = @{spawn_read("date '+%Y-%m-%d %H:%M:%S'")}[1];
$txt =~ s/\n//g;
printl( e("span", text($txt)) );
