#!/usr/bin/env perl
use strict;
use warnings;

require '../static/rpw_import.pl';
our $br;

allowed_methods(["GET"]);
print_headers({
    "Content-Type" => "text/html"
});

printl(e(
    "p", "content"
) . ea(
    "div", {
        "id" => "dam9as9add9ua9suda9u",
        "hx-get" => "/cgi-bin/cpu",
        "hx-trigger" => "load",
        "hx-swap" => "outerHTML",
    }, ""
));
