#!/usr/bin/env perl
use strict;
use warnings;

require '../static/common.pl';
our $br;

allowed_methods(["GET"]);
print_headers({
    "Content-Type" => "text/html"
});

printl(ea(
    "span", {
        "id" => "logo",
    }, "MinPanel"
) . e("span", ".............................................................................................................") . ea(
    "div", {
        "id" => "header-clock",
        "hx-get" => "/cgi-bin/clock",
        "hx-trigger" => "load, every 1s",
    }, ""
));
