#!/usr/bin/env perl
use strict;
use warnings;

require '../static/common.pl';
our $br;

# $ENV{"REQUEST_METHOD"}
# $ENV{"REQUEST_URI"}

allowed_methods(["GET"]);
print_headers({
    "Content-Type" => "text/html"
});

printl(set_title("Min Panel"));

printl(ea(
    "div", {
        "id" => "main",
    }, ea(
        "div", {
            "id" => "header",
            "class" => "pad",
            "hx-get" => "/cgi-bin/header",
            "hx-trigger" => "load",
        }, ""
    ) . ea(
        "div", {
            "id" => "sidebar-content-container",
        }, ea(
            "div", {
                "id" => "sidebar",
                "class" => "pad",
            }, "sdb"
        ) . ea(
            "div", {
                "id" => "content",
                "class" => "pad",
            }, "cnt"
        )
    )
));
