#!/usr/bin/env perl
use strict;
use warnings;

require '../static/common.pl';
our $br;

allowed_methods(["GET"]);
print_headers({
    "Content-Type" => "text/html"
});

printl(set_title("Min Panel"));

printl( ea("p", {"class" => "code"}, escape_spaces(text("Method: " . text($ENV{"REQUEST_METHOD"})))) );
printl( ea("p", {"class" => "code"}, escape_spaces(text("URI:    " . text($ENV{"REQUEST_URI"})))) );

printl( $br );

printl(ea(
    "p", {
        "hx-get" => "/cgi-bin/clock",
        "hx-trigger" => "load, every 1s",
        "class" => "code",
    }, ""
));
