#!/usr/bin/env perl
use strict;
use warnings;

require '../static/rpw_import.pl';
our $br;

allowed_methods(["GET"]);
print_headers({
    "Content-Type" => "text/html"
});

printl(e("p", "sidebar"));
